name: Void Linux

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: build
        uses: ./docker-action/
      - name: Archive gui binary
        uses: actions/upload-artifact@v3
        with:
          name: iso
          path: build.sh
